dist: trusty
sudo: required
language: python
python:
- '3.5'
- '3.6'
before-install:
- apt-get update -y
- apt-get install -y software-properties-common
- wget -qO - 'https://packages.confluent.io/deb/4.0/archive.key' | apt-key add -
- add-apt-repository "deb [arch=amd64] https://packages.confluent.io/deb/4.0 stable
  main"
- apt-get install -y librdkafka-dev librdkafka1
install:
- pip install tox-travis
script:
- tox
deploy:
  provider: pypi
  user: mazzafish
  password:
    secure: mF+n94ShlDuyc2sTgyIot1WmmF33vfjagHj2ID1NxISB+O/BvQyR1+TMirwoHUfh80tR1PqeEw502pgs9FerfZkKseG+nhL62eJxyJsMiubJ1UIS0qGdZJVk+GIGzysmOCb5G8IirZ2BG/XtkgsqTJV477OOTbrBUBrQ9MQ8S7qz3zMdyg1yxxvTLBxhkEaiPifaFtCpY/PCPgOmzFlQh7Jm5AlxDSo3m0OFJMtRvPEzijjsdruT8pxMICEa/CtMOh/KqIEH7V5aivr+MJvZvCcoqWz64Bku7jB0Id0cTqXCmD42iJZSqVkcX8s0DYm2gGCvGaaVsdjdHBq+UBwrtQ3CykbUSFU81560k2/G9n/t9uldvsDhHyCUqwxR8jP8JhnFRZn6k+jXwf5c7+m6n6GkMK3qMY2QnvwQuQaEpKW6r2G9uQKq4+sE3KJfTPnyIfftGSek1FHFte0NelCLDWv8//qrLfBKPLeA4T0PRni2NcG/5GAQMM9Dt0XwVwBlGRPBFcShphwdHHZ7l4Jb7mmWSz4ZmwY3vO05MK0HzSgPQMqxLMDq1whG/UFPUb4hWLAnJyqaQ9NVxp2JdKTTbRsONOUE/urzPgvt3x9TIzXbuY8joTjgxVWrOMXoTjC+Lm3hbso2NzqkKlq+LF7HYqw0t8Qw5u57cHy8HQ26oPE=
  distributions: sdist bdist_wheel
  on:
    tags: true
    branch: master
